import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" max-w-[100vw] min-h-[100vh] flex flex-col overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
